name: CI

on:
  push:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: Release Version
        required: false

# Builds:
# * Linux x86_64 Portable
# * Linux App Image
# * Mac x86_64 Portable
# * Mac aarch64 Portable
# * Mac Universal DMG
# * Windows x86_64 Portable
# * Windows x86_64 Installer
jobs:
  # Checks to see if we have an input, and stamps that onto the repo.
  # Determines if this is a release, and determines the official ref.
  version:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check_release.outputs.release }}
      ref: ${{ steps.check_release.outputs.ref }}
    steps:
      - name: Fetch Version
        id: tag
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi
      # - name: Update Tag
      #   uses: richardsimko/update-tag@v1
      #   if: ${{ steps.tag.outputs.version }}
      #   with:
      #     tag_name: ${{ steps.tag.outputs.version }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Check Release
        id: check_release
        run: |
          export REF=`git describe --match v[0-9]* HEAD --tags`
          echo "Build Version: $REF"
          [[ "$REF" != "" ]] && echo "ref=$REF" >> $GITHUB_OUTPUT
          if [[ `git describe --exact-match --match v[0-9]* HEAD --tags` ]]; then
            echo "release=$REF" >> $GITHUB_OUTPUT
            echo "Release Version: $REF"
          fi
  build_linux:
    name: Linux
    needs: [version]
    runs-on: ubuntu-latest
    container: ghcr.io/lite-xl/lite-xl-build-box:latest
    strategy:
      matrix:
        config:
        - { name: "GCC", cc: gcc, cxx: g++ }
        # - { name: "clang", cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      ARCH: x86_64
    steps:
      - name: Install Clang
        if: ${{ matrix.config.cc == 'clang' }}
        run: |
          apt-get update && apt-get install clang
      - name: System Information
        run: |
          bash --version
          $CC -v
      - name: Set Environment Variables
        if: ${{ matrix.config.cc == 'gcc' }}
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "INSTALL_NAME=lite-xl-${{ needs.version.outputs.ref }}-$ARCH-linux" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      # - name: Python Setup
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.9
      # - name: Update Packages
      #   run: sudo apt-get update
      # - name: Install Dependencies
      #   run: bash scripts/install-dependencies.sh --debug
      - name: Build
        run: scripts/build.sh --forcefallback --portable --addons --debug
      - name: Package
        if: ${{ matrix.config.cc == 'gcc' }}
        run: |
          cd build-$ARCH-linux && tar -cvf ../$INSTALL_NAME.tar lite-xl && cd .. && gzip $INSTALL_NAME.tar
          ls -l
          scripts/package-appimage.sh --debug --version ${{ needs.version.outputs.ref }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ matrix.config.cc == 'gcc' }}
        with:
          name: Linux Portable & AppImage
          path: |
            *.tar.gz
            *.AppImage

  build_macos:
    name: macOS
    needs: [version]
    runs-on: macos-11
    env:
      CC: clang
      CXX: clang++
      ARCHES: x86_64 arm64
    steps:
      - name: System Information
        run: |
          system_profiler SPSoftwareDataType
          bash --version
          gcc -v
          xcodebuild -version
      - name: Set Environment Variables
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "INSTALL_PREFIX=lite-xl-${{ needs.version.outputs.ref }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: scripts/install-dependencies.sh --debug
      - name: Build
        run: |
          for ARCH in $ARCHES; do
            [[ $(uname -m) != $ARCH ]] && echo "CROSS=--cross-arch $ARCH" >> "$GITHUB_ENV"
            scripts/build.sh --addons --debug --forcefallback $CROSS --portable
            tar -cvf $INSTALL_PREFIX-$ARCH-darwin.tar -C build-$ARCH-darwin lite-xl && gzip $INSTALL_PREFIX-$ARCH-darwin.tar
            scripts/build.sh --addons --debug --forcefallback $CROSS --bundle
          done
      - name: Create DMG Images
        run:
          export DMGS=""
          for ARCH in ARCHES; do;
            scripts/package-dmg.sh --version ${{ needs.version.outputs.ref }} --debug
            export DMGS="$DMGS $INSTALL_PREFIX-$ARCH-darwin"
          done
          scripts/package-universal-dmg.sh $DMGS
      - name: Upload Mac Images
        uses: actions/upload-artifact@v3
        with:
          name: macOS Portable and DMGs
          path: |
            *.dmg
            *.tar.gz

  build_windows_msys2:
    name: Windows
    needs: [version]
    runs-on: windows-2019
    strategy:
      matrix:
        config:
          # - {msystem: MINGW32, arch: i686}
          - {msystem: MINGW64, arch: x86_64}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.config.msystem }}
        install: >-
          base-devel
          git
          zip
          mingw-w64-${{ matrix.config.arch }}-gcc
          mingw-w64-${{ matrix.config.arch }}-meson
          mingw-w64-${{ matrix.config.arch }}-ninja
          mingw-w64-${{ matrix.config.arch }}-ca-certificates
          mingw-w64-${{ matrix.config.arch }}-ntldd
    - name: Set Environment Variables
      run: |
        bash --version
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        if [[ "${MSYSTEM}" == "MINGW64" ]]; then
          echo "INSTALL_NAME=lite-xl-${{ needs.version.outputs.ref }}-x86_64-windows" >> "$GITHUB_ENV"
        else
          echo "INSTALL_NAME=lite-xl-${{ needs.version.outputs.ref }}-x86-windows" >> "$GITHUB_ENV"
        fi
    - name: Build
      run: scripts/build.sh --addons -U --debug --forcefallback
    - name: Package
      run: |
        cd build-x86_64-windows && zip ../$INSTALL_NAME.zip -r lite-xl && cd ..
        scripts/package-innosetup.sh --debug --version ${{ needs.version.outputs.ref }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Portable & Installer
        path: ${{ env.INSTALL_NAME }}.zip

  build_windows_msvc:
    name: Windows (MSVC)
    needs: [version]
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          # - { target: x86, name: i686 }
          - { target: x64, name: x86_64 }
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch.target }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install meson and ninja
        run: pip install meson ninja
      - name: Set up environment variables
        run: |
          "INSTALL_NAME=lite-xl-${{ needs.version.outputs.ref }}-windows-msvc-${{ matrix.arch.name }}" >> $env:GITHUB_ENV
          "LUA_SUBPROJECT_PATH=subprojects/lua-5.4.4" >> $env:GITHUB_ENV
      - name: Configure
        run: |
          # Download the subprojects first so we can patch it before configuring.
          # This avoids reconfiguring the subprojects when compiling.
          meson subprojects download
          Get-Content -Path resources/windows/001-lua-unicode.diff -Raw | patch -d $env:LUA_SUBPROJECT_PATH -p1 --forward
          meson setup --wrap-mode=forcefallback build
      - name: Build
        run: |
          meson install -C build --destdir="../lite-xl"
      - name: Package
        run: |
          Remove-Item -Recurse -Force -Path "lite-xl/lib","lite-xl/include"
          Compress-Archive -Path lite-xl -DestinationPath "$env:INSTALL_NAME.zip"

  release:
    name: Create Release
    needs: [version, build_windows_msys2, build_macos, build_linux]
    runs-on: ubuntu-latest
    container: ghcr.io/lite-xl/lite-xl-build-box:latest
    if: ${{ needs.version.outputs.release }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Artfacts
        uses: actions/download-artifact@v3
        with:
          path: .
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.version.outputs.release }}
          name: Lite XL ${{ needs.version.outputs.release }}
          draft: true
          body_path: changelog.md
          generate_release_notes: true
          files: |
            *.tar.gz
            *.zip
            *.exe
            *.dmg
            *.AppImage
