name: OSX-Package

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master gh-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-macox:
    name: Build Mac OS X
    runs-on: macos-10.15
    strategy:
      matrix:
        config:
        - { name: "clang", cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install meson
          brew install ninja sdl2
      - name: configure package
        run:
          meson setup build --backend=xcode
      - name: build package
        working-directory: build
        run:
          xcodebuild -list
          xcodebuild -toolchain clang -configuration Release -target lite -scheme lite
          rm -rf Build/Products/Release/lite.app.dSYM
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Mac Lite-XL
          path: build/Build/Products/Release
